# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cdhitestC <- function(opts, name, showProgress) {
    .Call('_CellaRepertorium_cdhitestC', PACKAGE = 'CellaRepertorium', opts, name, showProgress)
}

cdhitC <- function(opts, name, showProgress) {
    .Call('_CellaRepertorium_cdhitC', PACKAGE = 'CellaRepertorium', opts, name, showProgress)
}

nSeqs <- function(files) {
    .Call('_CellaRepertorium_nSeqs', PACKAGE = 'CellaRepertorium', files)
}

getClusters <- function(I, P, X) {
    .Call('_CellaRepertorium_getClustersFromR', PACKAGE = 'CellaRepertorium', I, P, X)
}

createPanMatrix <- function(org, group) {
    .Call('_CellaRepertorium_createPanMatrix', PACKAGE = 'CellaRepertorium', org, group)
}

calcGroupInfo <- function(groupOrgs, nOrgs, threshold) {
    .Call('_CellaRepertorium_calcGroupInfo', PACKAGE = 'CellaRepertorium', groupOrgs, nOrgs, threshold)
}

findIn <- function(keys, lookup) {
    .Call('_CellaRepertorium_findIn', PACKAGE = 'CellaRepertorium', keys, lookup)
}

lkMatrix <- function(pX, jX, xX, selX, lowerLimit, upperLimit) {
    .Call('_CellaRepertorium_lkMatrix', PACKAGE = 'CellaRepertorium', pX, jX, xX, selX, lowerLimit, upperLimit)
}

lkMembers <- function(pX, jX, xX, selX, lowerLimit, upperLimit) {
    .Call('_CellaRepertorium_lkMembers', PACKAGE = 'CellaRepertorium', pX, jX, xX, selX, lowerLimit, upperLimit)
}

neighborhoodSim <- function(members, groups, organism, size, down, up, reverse, width, threshold, forceParalogues) {
    .Call('_CellaRepertorium_neighborhoodSim', PACKAGE = 'CellaRepertorium', members, groups, organism, size, down, up, reverse, width, threshold, forceParalogues)
}

mergeSims <- function(nI, nP, nX, sI, sP, sX, guideGroup) {
    .Call('_CellaRepertorium_mergeSims', PACKAGE = 'CellaRepertorium', nI, nP, nX, sI, sP, sX, guideGroup)
}

widthSim <- function(groups, width, threshold, progName, showProgress) {
    .Call('_CellaRepertorium_widthSim', PACKAGE = 'CellaRepertorium', groups, width, threshold, progName, showProgress)
}

getCliques <- function(edges, nNodes) {
    .Call('_CellaRepertorium_getCliques', PACKAGE = 'CellaRepertorium', edges, nNodes)
}

getPotentials <- function(down, up, pending, reverse, groupSplit, groups) {
    .Call('_CellaRepertorium_getPotentials', PACKAGE = 'CellaRepertorium', down, up, pending, reverse, groupSplit, groups)
}

groupHasParalogues <- function(groupMembers, org) {
    .Call('_CellaRepertorium_groupHasParalogues', PACKAGE = 'CellaRepertorium', groupMembers, org)
}

groupNeighbors <- function(down, up, groups, order) {
    .Call('_CellaRepertorium_groupNeighbors', PACKAGE = 'CellaRepertorium', down, up, groups, order)
}

mergeGroupsByNeighbors <- function(GOI, lookup) {
    .Call('_CellaRepertorium_mergeGroupsByNeighbors', PACKAGE = 'CellaRepertorium', GOI, lookup)
}

panSim <- function(P, I, names) {
    .Call('_CellaRepertorium_panSim', PACKAGE = 'CellaRepertorium', P, I, names)
}

