# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cdhitestC <- function(opts, name, showProgress) {
    .Call('_CellaRepertorium_cdhitestC', PACKAGE = 'CellaRepertorium', opts, name, showProgress)
}

cdhitC <- function(opts, name, showProgress) {
    .Call('_CellaRepertorium_cdhitC', PACKAGE = 'CellaRepertorium', opts, name, showProgress)
}

